
package ru.khmelev.tm.api.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-08T11:44:25.577+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "ClassNotFoundException", targetNamespace = "http://endpoint.api.tm.khmelev.ru/")
public class ClassNotFoundException_Exception extends java.lang.Exception {

    private ru.khmelev.tm.api.endpoint.ClassNotFoundException classNotFoundException;

    public ClassNotFoundException_Exception() {
        super();
    }

    public ClassNotFoundException_Exception(String message) {
        super(message);
    }

    public ClassNotFoundException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClassNotFoundException_Exception(String message, ru.khmelev.tm.api.endpoint.ClassNotFoundException classNotFoundException) {
        super(message);
        this.classNotFoundException = classNotFoundException;
    }

    public ClassNotFoundException_Exception(String message, ru.khmelev.tm.api.endpoint.ClassNotFoundException classNotFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.classNotFoundException = classNotFoundException;
    }

    public ru.khmelev.tm.api.endpoint.ClassNotFoundException getFaultInfo() {
        return this.classNotFoundException;
    }
}
