
package ru.khmelev.tm.api.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-05T18:56:38.867+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "IOException", targetNamespace = "http://endpoint.api.tm.khmelev.ru/")
public class IOException_Exception extends Exception {

    private ru.khmelev.tm.api.endpoint.IOException ioException;

    public IOException_Exception() {
        super();
    }

    public IOException_Exception(String message) {
        super(message);
    }

    public IOException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, ru.khmelev.tm.api.endpoint.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, ru.khmelev.tm.api.endpoint.IOException ioException, java.lang.Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public ru.khmelev.tm.api.endpoint.IOException getFaultInfo() {
        return this.ioException;
    }
}
