package ru.khmelev.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-08T11:44:24.736+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.khmelev.ru/", name = "IProjectEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IProjectEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlLoadJSONRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlLoadJSONResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlLoadJSON/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlLoadJSON", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadJSON")
    @ResponseWrapper(localName = "fasterXmlLoadJSONResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadJSONResponse")
    public void fasterXmlLoadJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbJSONSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbJSONSaveResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbJSONSave/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbJSONSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONSave")
    @ResponseWrapper(localName = "jaxbJSONSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONSaveResponse")
    public void jaxbJSONSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/clearEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/clearEntityResponse")
    @RequestWrapper(localName = "clearEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.ClearEntity")
    @ResponseWrapper(localName = "clearEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.ClearEntityResponse")
    public void clearEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbXmlSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbXmlSaveResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbXmlSave/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbXmlSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlSave")
    @ResponseWrapper(localName = "jaxbXmlSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlSaveResponse")
    public void jaxbXmlSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlLoadXMLRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlLoadXMLResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlLoadXML/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlLoadXML", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadXML")
    @ResponseWrapper(localName = "fasterXmlLoadXMLResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadXMLResponse")
    public void fasterXmlLoadXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/findEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/findEntityResponse")
    @RequestWrapper(localName = "findEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindEntity")
    @ResponseWrapper(localName = "findEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindEntityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.khmelev.tm.api.endpoint.Entity findEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/serializationLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/serializationLoadResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/serializationLoad/Fault/IOException"), @FaultAction(className = ClassNotFoundException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/serializationLoad/Fault/ClassNotFoundException")})
    @RequestWrapper(localName = "serializationLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationLoad")
    @ResponseWrapper(localName = "serializationLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationLoadResponse")
    public void serializationLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception, ClassNotFoundException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbXmlLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbXmlLoadResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbXmlLoad/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbXmlLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlLoad")
    @ResponseWrapper(localName = "jaxbXmlLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlLoadResponse")
    public void jaxbXmlLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/serializationSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/serializationSaveResponse")
    @RequestWrapper(localName = "serializationSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationSave")
    @ResponseWrapper(localName = "serializationSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationSaveResponse")
    public void serializationSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/soQrtRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/soQrtResponse")
    @RequestWrapper(localName = "soQrt", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SoQrt")
    @ResponseWrapper(localName = "soQrtResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SoQrtResponse")
    public void soQrt(
        @WebParam(name = "session", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session session,
        @WebParam(name = "list", targetNamespace = "")
        java.util.List<java.lang.Object> list,
        @WebParam(name = "sortParameter", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Sort sortParameter
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbJSONLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbJSONLoadResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/jaxbJSONLoad/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbJSONLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONLoad")
    @ResponseWrapper(localName = "jaxbJSONLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONLoadResponse")
    public void jaxbJSONLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/findAllNameRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/findAllNameResponse")
    @RequestWrapper(localName = "findAllName", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllName")
    @ResponseWrapper(localName = "findAllNameResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> findAllName(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/findAllDescriptionRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/findAllDescriptionResponse")
    @RequestWrapper(localName = "findAllDescription", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllDescription")
    @ResponseWrapper(localName = "findAllDescriptionResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> findAllDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlSaveXMLRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlSaveXMLResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlSaveXML/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlSaveXML", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveXML")
    @ResponseWrapper(localName = "fasterXmlSaveXMLResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveXMLResponse")
    public void fasterXmlSaveXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/editEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/editEntityResponse")
    @RequestWrapper(localName = "editEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.EditEntity")
    @ResponseWrapper(localName = "editEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.EditEntityResponse")
    public void editEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Entity arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/createEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/createEntityResponse")
    @RequestWrapper(localName = "createEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.CreateEntity")
    @ResponseWrapper(localName = "createEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.CreateEntityResponse")
    public void createEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Entity arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/removeEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/removeEntityResponse")
    @RequestWrapper(localName = "removeEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.RemoveEntity")
    @ResponseWrapper(localName = "removeEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.RemoveEntityResponse")
    public void removeEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/findAllRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/findAllResponse")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> findAll(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlSaveJSONRequest", output = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlSaveJSONResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IProjectEndpoint/fasterXmlSaveJSON/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlSaveJSON", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveJSON")
    @ResponseWrapper(localName = "fasterXmlSaveJSONResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveJSONResponse")
    public void fasterXmlSaveJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;
}
