package ru.khmelev.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-10T12:14:05.528+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.khmelev.ru/", name = "ISaveAndLoadEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ISaveAndLoadEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/fasterXmlLoadJSONRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/fasterXmlLoadJSONResponse")
    @RequestWrapper(localName = "fasterXmlLoadJSON", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadJSON")
    @ResponseWrapper(localName = "fasterXmlLoadJSONResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadJSONResponse")
    public void fasterXmlLoadJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/jaxbJSONSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/jaxbJSONSaveResponse")
    @RequestWrapper(localName = "jaxbJSONSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONSave")
    @ResponseWrapper(localName = "jaxbJSONSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONSaveResponse")
    public void jaxbJSONSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/fasterXmlSaveXMLRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/fasterXmlSaveXMLResponse")
    @RequestWrapper(localName = "fasterXmlSaveXML", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveXML")
    @ResponseWrapper(localName = "fasterXmlSaveXMLResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveXMLResponse")
    public void fasterXmlSaveXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/fasterXmlLoadXMLRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/fasterXmlLoadXMLResponse")
    @RequestWrapper(localName = "fasterXmlLoadXML", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadXML")
    @ResponseWrapper(localName = "fasterXmlLoadXMLResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadXMLResponse")
    public void fasterXmlLoadXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/jaxbXmlSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/jaxbXmlSaveResponse")
    @RequestWrapper(localName = "jaxbXmlSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlSave")
    @ResponseWrapper(localName = "jaxbXmlSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlSaveResponse")
    public void jaxbXmlSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/serializationLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/serializationLoadResponse")
    @RequestWrapper(localName = "serializationLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationLoad")
    @ResponseWrapper(localName = "serializationLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationLoadResponse")
    public void serializationLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/jaxbXmlLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/jaxbXmlLoadResponse")
    @RequestWrapper(localName = "jaxbXmlLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlLoad")
    @ResponseWrapper(localName = "jaxbXmlLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlLoadResponse")
    public void jaxbXmlLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/fasterXmlSaveJSONRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/fasterXmlSaveJSONResponse")
    @RequestWrapper(localName = "fasterXmlSaveJSON", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveJSON")
    @ResponseWrapper(localName = "fasterXmlSaveJSONResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveJSONResponse")
    public void fasterXmlSaveJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/serializationSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/serializationSaveResponse")
    @RequestWrapper(localName = "serializationSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationSave")
    @ResponseWrapper(localName = "serializationSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationSaveResponse")
    public void serializationSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/jaxbJSONLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/ISaveAndLoadEndpoint/jaxbJSONLoadResponse")
    @RequestWrapper(localName = "jaxbJSONLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONLoad")
    @ResponseWrapper(localName = "jaxbJSONLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONLoadResponse")
    public void jaxbJSONLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );
}
