package ru.khmelev.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-08T11:44:25.007+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.khmelev.ru/", name = "ITaskEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ITaskEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlLoadJSONRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlLoadJSONResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlLoadJSON/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlLoadJSON", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadJSON")
    @ResponseWrapper(localName = "fasterXmlLoadJSONResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadJSONResponse")
    public void fasterXmlLoadJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbJSONSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbJSONSaveResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbJSONSave/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbJSONSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONSave")
    @ResponseWrapper(localName = "jaxbJSONSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONSaveResponse")
    public void jaxbJSONSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/clearEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/clearEntityResponse")
    @RequestWrapper(localName = "clearEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.ClearEntity")
    @ResponseWrapper(localName = "clearEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.ClearEntityResponse")
    public void clearEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbXmlSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbXmlSaveResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbXmlSave/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbXmlSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlSave")
    @ResponseWrapper(localName = "jaxbXmlSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlSaveResponse")
    public void jaxbXmlSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlLoadXMLRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlLoadXMLResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlLoadXML/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlLoadXML", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadXML")
    @ResponseWrapper(localName = "fasterXmlLoadXMLResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadXMLResponse")
    public void fasterXmlLoadXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/listTaskFromProjectRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/listTaskFromProjectResponse")
    @RequestWrapper(localName = "listTaskFromProject", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.ListTaskFromProject")
    @ResponseWrapper(localName = "listTaskFromProjectResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.ListTaskFromProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.khmelev.tm.api.endpoint.Task> listTaskFromProject(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/findEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/findEntityResponse")
    @RequestWrapper(localName = "findEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindEntity")
    @ResponseWrapper(localName = "findEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindEntityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.khmelev.tm.api.endpoint.Entity findEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/serializationLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/serializationLoadResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/serializationLoad/Fault/IOException"), @FaultAction(className = ClassNotFoundException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/serializationLoad/Fault/ClassNotFoundException")})
    @RequestWrapper(localName = "serializationLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationLoad")
    @ResponseWrapper(localName = "serializationLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationLoadResponse")
    public void serializationLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception, ClassNotFoundException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbXmlLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbXmlLoadResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbXmlLoad/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbXmlLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlLoad")
    @ResponseWrapper(localName = "jaxbXmlLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlLoadResponse")
    public void jaxbXmlLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/serializationSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/serializationSaveResponse")
    @RequestWrapper(localName = "serializationSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationSave")
    @ResponseWrapper(localName = "serializationSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationSaveResponse")
    public void serializationSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/soQrtRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/soQrtResponse")
    @RequestWrapper(localName = "soQrt", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SoQrt")
    @ResponseWrapper(localName = "soQrtResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SoQrtResponse")
    public void soQrt(
        @WebParam(name = "session", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session session,
        @WebParam(name = "list", targetNamespace = "")
        java.util.List<java.lang.Object> list,
        @WebParam(name = "sortParameter", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Sort sortParameter
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbJSONLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbJSONLoadResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/jaxbJSONLoad/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbJSONLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONLoad")
    @ResponseWrapper(localName = "jaxbJSONLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONLoadResponse")
    public void jaxbJSONLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/findAllNameRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/findAllNameResponse")
    @RequestWrapper(localName = "findAllName", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllName")
    @ResponseWrapper(localName = "findAllNameResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> findAllName(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/findAllDescriptionRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/findAllDescriptionResponse")
    @RequestWrapper(localName = "findAllDescription", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllDescription")
    @ResponseWrapper(localName = "findAllDescriptionResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> findAllDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/removeAllTaskFromProjectRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/removeAllTaskFromProjectResponse")
    @RequestWrapper(localName = "removeAllTaskFromProject", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.RemoveAllTaskFromProject")
    @ResponseWrapper(localName = "removeAllTaskFromProjectResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.RemoveAllTaskFromProjectResponse")
    public void removeAllTaskFromProject(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlSaveXMLRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlSaveXMLResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlSaveXML/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlSaveXML", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveXML")
    @ResponseWrapper(localName = "fasterXmlSaveXMLResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveXMLResponse")
    public void fasterXmlSaveXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/editEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/editEntityResponse")
    @RequestWrapper(localName = "editEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.EditEntity")
    @ResponseWrapper(localName = "editEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.EditEntityResponse")
    public void editEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Entity arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/findAllRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/findAllResponse")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> findAll(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/removeEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/removeEntityResponse")
    @RequestWrapper(localName = "removeEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.RemoveEntity")
    @ResponseWrapper(localName = "removeEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.RemoveEntityResponse")
    public void removeEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/createEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/createEntityResponse")
    @RequestWrapper(localName = "createEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.CreateEntity")
    @ResponseWrapper(localName = "createEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.CreateEntityResponse")
    public void createEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Entity arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlSaveJSONRequest", output = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlSaveJSONResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/ITaskEndpoint/fasterXmlSaveJSON/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlSaveJSON", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveJSON")
    @ResponseWrapper(localName = "fasterXmlSaveJSONResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveJSONResponse")
    public void fasterXmlSaveJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;
}
