package ru.khmelev.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-08T11:44:25.577+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.khmelev.ru/", name = "IUserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IUserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/userLoginRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/userLoginResponse")
    @RequestWrapper(localName = "userLogin", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.UserLogin")
    @ResponseWrapper(localName = "userLoginResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.UserLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.khmelev.tm.api.endpoint.Session userLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlLoadJSONRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlLoadJSONResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlLoadJSON/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlLoadJSON", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadJSON")
    @ResponseWrapper(localName = "fasterXmlLoadJSONResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadJSONResponse")
    public void fasterXmlLoadJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbJSONSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbJSONSaveResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbJSONSave/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbJSONSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONSave")
    @ResponseWrapper(localName = "jaxbJSONSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONSaveResponse")
    public void jaxbJSONSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/clearEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/clearEntityResponse")
    @RequestWrapper(localName = "clearEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.ClearEntity")
    @ResponseWrapper(localName = "clearEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.ClearEntityResponse")
    public void clearEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbXmlSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbXmlSaveResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbXmlSave/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbXmlSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlSave")
    @ResponseWrapper(localName = "jaxbXmlSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlSaveResponse")
    public void jaxbXmlSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlLoadXMLRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlLoadXMLResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlLoadXML/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlLoadXML", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadXML")
    @ResponseWrapper(localName = "fasterXmlLoadXMLResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlLoadXMLResponse")
    public void fasterXmlLoadXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/findEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/findEntityResponse", fault = {@FaultAction(className = SerialException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/findEntity/Fault/SerialException")})
    @RequestWrapper(localName = "findEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindEntity")
    @ResponseWrapper(localName = "findEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindEntityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.khmelev.tm.api.endpoint.Entity findEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws SerialException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/serializationLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/serializationLoadResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/serializationLoad/Fault/IOException"), @FaultAction(className = ClassNotFoundException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/serializationLoad/Fault/ClassNotFoundException")})
    @RequestWrapper(localName = "serializationLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationLoad")
    @ResponseWrapper(localName = "serializationLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationLoadResponse")
    public void serializationLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception, ClassNotFoundException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbXmlLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbXmlLoadResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbXmlLoad/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbXmlLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlLoad")
    @ResponseWrapper(localName = "jaxbXmlLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbXmlLoadResponse")
    public void jaxbXmlLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/userLogOutRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/userLogOutResponse")
    @RequestWrapper(localName = "userLogOut", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.UserLogOut")
    @ResponseWrapper(localName = "userLogOutResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.UserLogOutResponse")
    public void userLogOut(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/serializationSaveRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/serializationSaveResponse")
    @RequestWrapper(localName = "serializationSave", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationSave")
    @ResponseWrapper(localName = "serializationSaveResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.SerializationSaveResponse")
    public void serializationSave(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbJSONLoadRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbJSONLoadResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/jaxbJSONLoad/Fault/JAXBException")})
    @RequestWrapper(localName = "jaxbJSONLoad", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONLoad")
    @ResponseWrapper(localName = "jaxbJSONLoadResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.JaxbJSONLoadResponse")
    public void jaxbJSONLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/getUserFromSessionRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/getUserFromSessionResponse")
    @RequestWrapper(localName = "getUserFromSession", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.GetUserFromSession")
    @ResponseWrapper(localName = "getUserFromSessionResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.GetUserFromSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.khmelev.tm.api.endpoint.User getUserFromSession(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/getNameRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/getNameResponse")
    @RequestWrapper(localName = "getName", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.GetNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlSaveXMLRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlSaveXMLResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlSaveXML/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlSaveXML", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveXML")
    @ResponseWrapper(localName = "fasterXmlSaveXMLResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveXMLResponse")
    public void fasterXmlSaveXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/editEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/editEntityResponse")
    @RequestWrapper(localName = "editEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.EditEntity")
    @ResponseWrapper(localName = "editEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.EditEntityResponse")
    public void editEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Entity arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/getIdRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/getIdResponse")
    @RequestWrapper(localName = "getId", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.GetId")
    @ResponseWrapper(localName = "getIdResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.GetIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getId(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/findAllRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/findAllResponse")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> findAll(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/removeEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/removeEntityResponse")
    @RequestWrapper(localName = "removeEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.RemoveEntity")
    @ResponseWrapper(localName = "removeEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.RemoveEntityResponse")
    public void removeEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/createEntityRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/createEntityResponse")
    @RequestWrapper(localName = "createEntity", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.CreateEntity")
    @ResponseWrapper(localName = "createEntityResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.CreateEntityResponse")
    public void createEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Entity arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlSaveJSONRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlSaveJSONResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/fasterXmlSaveJSON/Fault/IOException")})
    @RequestWrapper(localName = "fasterXmlSaveJSON", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveJSON")
    @ResponseWrapper(localName = "fasterXmlSaveJSONResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.FasterXmlSaveJSONResponse")
    public void fasterXmlSaveJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/userSetPasswordRequest", output = "http://endpoint.api.tm.khmelev.ru/IUserEndpoint/userSetPasswordResponse")
    @RequestWrapper(localName = "userSetPassword", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.UserSetPassword")
    @ResponseWrapper(localName = "userSetPasswordResponse", targetNamespace = "http://endpoint.api.tm.khmelev.ru/", className = "ru.khmelev.tm.api.endpoint.UserSetPasswordResponse")
    public void userSetPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.khmelev.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
