package ru.khmelev.tm.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import ru.khmelev.tm.api.endpoint.ISaveAndLoadEndpoint;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-10T12:14:05.550+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "SaveAndLoadEndpointService",
                  wsdlLocation = "http://localhost:2019/SaveAndLoadEndpoint?wsdl",
                  targetNamespace = "http://endpoint.tm.khmelev.ru/")
public class SaveAndLoadEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.tm.khmelev.ru/", "SaveAndLoadEndpointService");
    public final static QName SaveAndLoadEndpointPort = new QName("http://endpoint.tm.khmelev.ru/", "SaveAndLoadEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:2019/SaveAndLoadEndpoint?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SaveAndLoadEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:2019/SaveAndLoadEndpoint?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SaveAndLoadEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SaveAndLoadEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaveAndLoadEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SaveAndLoadEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SaveAndLoadEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SaveAndLoadEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ISaveAndLoadEndpoint
     */
    @WebEndpoint(name = "SaveAndLoadEndpointPort")
    public ISaveAndLoadEndpoint getSaveAndLoadEndpointPort() {
        return super.getPort(SaveAndLoadEndpointPort, ISaveAndLoadEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISaveAndLoadEndpoint
     */
    @WebEndpoint(name = "SaveAndLoadEndpointPort")
    public ISaveAndLoadEndpoint getSaveAndLoadEndpointPort(WebServiceFeature... features) {
        return super.getPort(SaveAndLoadEndpointPort, ISaveAndLoadEndpoint.class, features);
    }

}
